package registroestudiantes;

public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new java.awt.TextField();
        txtNota2 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        txtNota1 = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        txtNota3 = new java.awt.TextField();
        buttonLimpiar = new java.awt.Button();
        button1 = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setText("Datos del Estudiante");

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        txtNota2.setForeground(new java.awt.Color(51, 51, 51));
        txtNota2.addActionListener(this::txtNota2ActionPerformed);

        jLabel4.setText("Primera Nota:");

        txtNota1.setForeground(new java.awt.Color(51, 51, 51));
        txtNota1.addActionListener(this::txtNota1ActionPerformed);

        jLabel5.setText("Segunda Nota:");

        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel6.setText("Tercera Nota:");

        txtNota3.setForeground(new java.awt.Color(51, 51, 51));
        txtNota3.addActionListener(this::txtNota3ActionPerformed);

        buttonLimpiar.setActionCommand("button 1");
        buttonLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        buttonLimpiar.setLabel("Limpiar Campos");
        buttonLimpiar.addActionListener(this::buttonLimpiarActionPerformed);

        button1.setActionCommand("button 2");
        button1.setBackground(new java.awt.Color(204, 255, 255));
        button1.setForeground(new java.awt.Color(51, 51, 51));
        button1.setLabel("Calcular y Registrar");
        button1.addActionListener(this::button1ActionPerformed);

        jLabel7.setText("Estudiantes Registrados");

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Primera Nota", "Segunda Nota", "Tercera Nota", "Definitiva", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota3ActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        nombre = capitalizarNombre(nombre);
        
        if (codigo.isEmpty() || nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
            "Debe ingresar el código y el nombre del estudiante.",
            "Datos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        if (existeCodigo(codigo)) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ya existe un estudiante registrado con el código \"" + codigo + "\".",
            "Código duplicado", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Double nota1 = validarNota(txtNota1.getText().trim(), "Primera nota");
            if (nota1 == null) return;
        Double nota2 = validarNota(txtNota2.getText().trim(), "Segunda nota");
            if (nota2 == null) return;
        Double nota3 = validarNota(txtNota3.getText().trim(), "Tercera nota");
            if (nota3 == null) return;

        double definitiva = (nota1 * 0.30) + (nota2 * 0.30) + (nota3 * 0.40);
        definitiva = Math.round(definitiva * 100.0) / 100.0;

        String estado = (definitiva >= 3.0) ? "Aprobó" : "Reprobó";

        javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tablaEstudiantes.getModel();
        modelo.addRow(new Object[]{codigo, nombre, nota1, nota2, nota3, definitiva, estado});

        limpiarCampos();
    }//GEN-LAST:event_button1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }
    private Double validarNota(String texto, String nombreCampo) {
        if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "El campo \"" + nombreCampo + "\" no puede estar vacío.",
                "Dato faltante", javax.swing.JOptionPane.WARNING_MESSAGE);
        return null;
    }
        try {
            double valor = Double.parseDouble(texto.replace(",", "."));
        if (valor < 0.0 || valor > 5.0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    nombreCampo + " debe estar entre 0.0 y 5.0.",
                    "Nota fuera de rango", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return valor;
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                nombreCampo + " debe ser un valor numérico válido.",
                "Formato inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        return null;
    }
}
    private boolean existeCodigo(String codigo) {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tablaEstudiantes.getModel();
    for (int i = 0; i < modelo.getRowCount(); i++) {
        Object valorCelda = modelo.getValueAt(i, 0); // columna 0 = Código
        if (valorCelda != null && valorCelda.toString().equalsIgnoreCase(codigo)) {
            return true;
        }
    }
    return false;
}
    private String capitalizarNombre(String texto) {
        if (texto.isEmpty()) {
        return texto;
    }
    String[] palabras = texto.toLowerCase().split("\\s+");
    StringBuilder resultado = new StringBuilder();
        for (String palabra : palabras) {
            if (!palabra.isEmpty()) {
            resultado.append(Character.toUpperCase(palabra.charAt(0)))
                      .append(palabra.substring(1))
                      .append(" ");
        }
    }
    return resultado.toString().trim();
}
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        txtCodigo.requestFocus();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button buttonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private java.awt.TextField txtCodigo;
    private java.awt.TextField txtNombre;
    private java.awt.TextField txtNota1;
    private java.awt.TextField txtNota2;
    private java.awt.TextField txtNota3;
    // End of variables declaration//GEN-END:variables
}

